version: "3.8"
services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: app_user
      DB_PASSWORD: password
      DB_NAME: app_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

volumes:
  db_data:
